### ISSUE TITLE
handling nonexistent .list files

### ISSUE THREAD

**Issue by yakra** [TravelMapping/DataProcessing#525]
Not a problem in production, since by default siteupdate processes .list files found in the UserData repo.
Only a problem if the `-U` or `--userlist` argument is used to specify an invalid username.
Should be an easy enough fix.

* **Python:**
  ```
  [89.9] Processing traveler list files:
  DAVE.list Traceback (most recent call last):
    File "./siteupdate.py", line 3229, in <module>
      traveler_lists.append(TravelerList(t,update,el,args.userlistfilepath))
    File "./siteupdate.py", line 1415, in __init__
      with open(path+"/"+travelername,"rt", encoding='UTF-8') as file:
  FileNotFoundError: [Errno 2] No such file or directory: '/home/yakra/ytm/UserData/list_files/DAVE.list'
  ```
* **C++** can run to completion, reading garbage from a random memory location, zeroing out another random byte in memory in the process.
  ```
  Log file created at: Mon Apr 25 18:49:10 2022
  Incorrect format line (4 or 6 fields expected, found 1): 
  Processed 0 good lines marking 0 segments traveled.
  Clinched Highway Statistics
  Overall in active systems: 0.00 of 953328.25 mi (0.00%)
  Overall in active+preview systems: 0.00 of 1345492.71 mi (0.00%)
  Overall by region: (each line reports active only then active+preview)
  
  Traveled 0 of 257 (0.0%), Clinched 0 of 257 (0.0%) active systems
  Traveled 0 of 87 (0.0%), Clinched 0 of 87 (0.0%) preview systems
  
  Most recent updates for listed routes:
  ```

**Comment by yakra** [comment]
Since `-U` / `--userlist` will only be used by developers for testing purposes, the simplest approach is to just catch the error and terminate immediately. No need to try to get siteupdate to run to completion without the intended data.
